name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build
    - name: Commit
      run: |
        git config --global user.email "57046712+not-lucky@users.noreply.github.com"
        git config --global user.name "not-lucky"
        git add .
        git commit -m "Built successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HMMMM_GITHUB_TOKEN }}
