#自动调用API保活，加密版
name: Go Builder

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#    branches: 
#      - master

  watch:
    types: [started]
   
jobs:
  build:
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.15.6'
    - name: Test Api #Api调用
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        go build
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email "57046712+not-lucky@users.noreply.github.com"
        git config --global user.name "not-lucky"
        git add .
        git commit -m "Built successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HMMMM_GITHUB_TOKEN }}
